build:
  image: teaci/msys$$arch
  pull: true
  shell: $$prefix$$arch
  commands:
    - ./bootstrap
    - ./configure
    - make
    - make check

matrix:
  prefix:
    - msys
    - mingw
  arch:
    - 32
    - 64
