From: Kirill Simonov <xi@gamma.dn.ua>
To: yaml-core@lists.sourceforge.net
Subject: LibYAML-0.0.1: The initial release

I'd like to present the initial release of LibYAML, a YAML parser and emitter
written in C.

LibYAML homepage:   http://pyyaml.org/wiki/LibYAML
TAR.GZ package:     http://pyyaml.org/download/libyaml/yaml-0.0.1.tar.gz
SVN repository:     http://svn.pyyaml.org/libyaml
Bug tracker:        http://pyyaml.org/newticket?component=libyaml

The library is functionally complete, but the documentation is scarce and the
API is subject to change.  For more information, you may check the project
homepage, the doxygen-generated documentation in the `doc` directory of the
source distribution, and the examples `tests/example-reformatter.c` and
`tests/example-deconstructor.c`.

LibYAML is written by Kirill Simonov <xi@resolvent.net>.  It is released
under the MIT license.  See the file LICENSE for more details.

This project is developed for Python Software Foundation as a part of
Google Summer of Code under the mentorship of Clark Evans.
