From: Kirill Simonov <xi@gamma.dn.ua>
To: yaml-core@lists.sourceforge.net
Subject: LibYAML-0.1.2: A minor bugfix release

This is a minor bugfix release of LibYAML, a YAML parser and emitter
written in C.

LibYAML homepage:   http://pyyaml.org/wiki/LibYAML
TAR.GZ package:     http://pyyaml.org/download/libyaml/yaml-0.1.2.tar.gz
SVN repository:     http://svn.pyyaml.org/libyaml/branches/stable
Bug tracker:        http://pyyaml.org/newticket?component=libyaml

The library is functionally complete, but the documentation is scarce and the
API is subject to change.  For more information, you may check the project
homepage, the doxygen-generated documentation in the `doc` directory of the
source distribution, and examples in the `tests` directory.

LibYAML is written by Kirill Simonov <xi@resolvent.net>.  It is released
under the MIT license.  See the file LICENSE for more details.

