name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./bootstrap
    - run: ./configure
    - run: make
    - run: make check
    - run: make test
    - run: make distcheck
